#!/usr/bin/env python3

from glob import glob
from PIL import Image
from os import chdir
chdir('original')
for item in sorted(glob('*.jpg')):
    image = Image.open(item)
    prefix = '{{site.baseurl}}/res/img/gallery'
    print('<div class="item"><img loading="lazy" src="{}/thumbnail/thumb_{}" data-src="{}/original/{}" data-width="{}" data-height="{}"></div>'.format(prefix,item,prefix,item,image.size[0],image.size[1]))